ALTER TABLE T_DEPOSIT
  ADD( UPD_BY VARCHAR2(10),
   REF_NUM VARCHAR2(25),
   APPROVED_DT DATE,
   APPROVED_BY VARCHAR2(10),
   APPROVED_STS CHAR(1),
   SEQNO NUMBER );

  
  UPDATE T_DEPOSIT set APPROVED_STS = 'A';



