ALTER TABLE T_TRX_FOREIGN ADD(
   UPD_DT DATE,
  UPD_BY VARCHAR2(10),
  APPROVED_DT DATE,
   APPROVED_BY VARCHAR2(10),
   APPROVED_STAT CHAR(1),
   SEQNO NUMBER);
  

 UPDATE T_TRX_FOREIGN SET APPROVED_STAT ='A';
   
