ALTER TABLE MST_MAP_MKBD ADD(
   UPD_DT DATE,
   CRE_DT DATE,
   USER_ID VARCHAR2(10),
	UPD_BY VARCHAR2(10),
	APPROVED_DT DATE,
   APPROVED_BY VARCHAR2(10),
   APPROVED_STAT CHAR(1));
   
   
   ALTER TABLE MST_MAP_MKBD MODIFY (SOURCE NOT NULL);
   
   UPDATE MST_MAP_MKBD SET APPROVED_STAT ='A';
 