  
   ALTER TABLE T_REK_DANA_KSEI MODIFY REK_DANA VARCHAR2(25);
   ALTER TABLE T_REK_DANA_KSEI_BAK MODIFY REK_DANA VARCHAR2(25);
   
   
   
   
   ALTER TABLE T_REK_DANA_KSEI ADD(KSEI_DATE DATE, USER_ID  VARCHAR2(10));

ALTER TABLE T_REK_DANA_KSEI_HIST ADD(KSEI_DATE DATE, USER_ID  VARCHAR2(10));


RENAME T_REK_DANA_KSEI_BAK TO T_REK_DANA_KSEI_HIST;