ALTER TABLE T_HAIRCUT_KOMITE add(
   UPD_DT DATE,
   USER_ID VARCHAR2(10),
  UPD_BY VARCHAR2(10),
  APPROVED_DT DATE,
   APPROVED_BY VARCHAR2(10),
   APPROVED_STAT CHAR(1));
 
 UPDATE T_HAIRCUT_KOMITE SET APPROVED_STAT = 'A';
   