
SET SERVEROUTPUT ON
DECLARE

CURSOR QUERY_DATA IS
SELECT UPDATE_DATE,UPDATE_SEQ,C.CLIENT_CD,A.* FROM IPNEXTG.t_H2H_REF_DETAIL A, IPNEXTG.t_H2H_REF_HEADER B, IPNEXTG.MST_CLIENT_FLACCT C,
(
SELECT MAX(CLIENT_CD)CLIENT_CD, UPDATE_DATE,UPDATE_SEQ FROM
(
  SELECT DECODE(FIELD_NAME,'CLIENT_CD',FIELD_VALUE,NULL)CLIENT_CD,
  H.UPDATE_DATE,H.UPDATE_SEQ
  FROM IPNEXTG.T_MANY_DETAIL D JOIN IPNEXTG.T_MANY_HEADER H ON D.UPDATE_DATE=H.UPDATE_DATE
  AND D.UPDATE_SEQ=H.UPDATE_SEQ
  AND H.APPROVED_STATUS='E'
  AND D.TABLE_NAME='T_PAYRECH'
  AND D.FIELD_NAME='CLIENT_CD'
  AND D.RECORD_SEQ=1
  AND MENU_NAME='GENERATE VOUCHER TRANSFER RDI'
)
GROUP BY UPDATE_DATE,UPDATE_SEQ
)BX
WHERE A.TRF_ID=B.TRF_ID
AND A.RDI_ACCT=C.BANK_ACCT_NUM
AND B.TRF_DATE=TRUNC(SYSDATE)
AND A.STATUS='01'
AND A.TRF_AMT=100
AND BX.CLIENT_CD=C.CLIENT_CD
ORDER  BY UPDATE_SEQ;

p_error_code NUMBER;
p_error_msg VARCHAR2(200);
p_menu_name							T_MANY_HEADER.menu_name%TYPE:='GENERATE VOUCHER TRANSFER RDI';
p_reject_user_id				  		T_MANY_HEADER.user_id%TYPE;
p_reject_ip_address 		 			T_MANY_HEADER.ip_address%TYPE;
p_reject_reason						T_MANY_HEADER.reject_reason%TYPE;
BEGIN

FOR REC IN QUERY_DATA LOOP

 SP_T_PAYRECH_REJECT (
	   p_menu_name,
	   REC.UPDATE_DATE,
	   REC.UPDATE_SEQ,
	   'AS',--p_reject_user_id,
	   '192.168.2.169',--p_reject_ip_address,
	   'VOUCHER SALAH',--p_reject_reason,
	   p_error_code,
	   p_error_msg);
     
END LOOP;     
     
END;
