SELECT 
TO_CHAR((SELECT to_date(FIELD_VALUE,'yyyy-mm-dd hh24:mi:ss') FROM T_MANY_DETAIL DA 
        WHERE DA.TABLE_NAME = 'T_OLT_LOGIN' 
        AND DA.UPDATE_DATE = DD.UPDATE_DATE
        AND DA.UPDATE_SEQ = DD.UPDATE_SEQ
        AND DA.FIELD_NAME = 'PERIOD_END_DATE'
        AND DA.RECORD_SEQ = DD.RECORD_SEQ),'YYYY-MM-DD') PERIOD_END_DATE, 
(SELECT FIELD_VALUE FROM T_MANY_DETAIL DA 
        WHERE DA.TABLE_NAME = 'T_OLT_LOGIN' 
        AND DA.UPDATE_DATE = DD.UPDATE_DATE
        AND DA.UPDATE_SEQ = DD.UPDATE_SEQ
        AND DA.FIELD_NAME = 'CLIENT_CD'
        AND DA.RECORD_SEQ = DD.RECORD_SEQ) CLIENT_CD, 
(SELECT FIELD_VALUE FROM T_MANY_DETAIL DA 
        WHERE DA.TABLE_NAME = 'T_OLT_LOGIN' 
        AND DA.UPDATE_DATE = DD.UPDATE_DATE
        AND DA.UPDATE_SEQ = DD.UPDATE_SEQ
        AND DA.FIELD_NAME = 'FEE_FLG'
        AND DA.RECORD_SEQ = DD.RECORD_SEQ) FEE_FLG,
DECODE(M.SUSP_STAT,'C',0,(SELECT FIELD_VALUE FROM T_MANY_DETAIL DA 
        WHERE DA.TABLE_NAME = 'T_OLT_LOGIN' 
        AND DA.UPDATE_DATE = DD.UPDATE_DATE
        AND DA.UPDATE_SEQ =  DD.UPDATE_SEQ
        AND DA.FIELD_NAME = 'INFO_FEE'
        AND DA.RECORD_SEQ = DD.RECORD_SEQ)) INFO_FEE,
M.CLIENT_NAME, M.BRANCH_CODE,
'N' FLG, DECODE(M.SUSP_STAT,'C','CLOSED','')KETERANGAN

FROM MST_CLIENT M, T_MANY_DETAIL DD, T_MANY_HEADER HH WHERE DD.TABLE_NAME = 'T_OLT_LOGIN' AND DD.UPDATE_DATE = HH.UPDATE_DATE
                      AND DD.UPDATE_SEQ = HH.UPDATE_SEQ
           AND (SELECT FIELD_VALUE FROM T_MANY_DETAIL DA 
        WHERE DA.TABLE_NAME = 'T_OLT_LOGIN' 
        AND DA.UPDATE_DATE = DD.UPDATE_DATE
        AND DA.UPDATE_SEQ = DD.UPDATE_SEQ
        AND DA.FIELD_NAME = 'CLIENT_CD'
        AND DA.RECORD_SEQ = DD.RECORD_SEQ) = M.CLIENT_CD and 
        (SELECT FIELD_VALUE FROM T_MANY_DETAIL DA 
        WHERE DA.TABLE_NAME = 'T_OLT_LOGIN' 
        AND DA.UPDATE_DATE = DD.UPDATE_DATE
        AND DA.UPDATE_SEQ =  DD.UPDATE_SEQ
        AND DA.FIELD_NAME = 'INFO_FEE'
        AND DA.RECORD_SEQ = DD.RECORD_SEQ)>0
        AND dd.field_name='PERIOD_END_DATE';