CREATE OR REPLACE
  FUNCTION F_CHECK_CIFS_RDI(
      P_CIFS MST_CLIENT.CIFS%TYPE )
    RETURN NUMBER
  IS
    V_CNT NUMBER(2);
    V_ERR EXCEPTION;
  BEGIN
  
    SELECT COUNT(*)
    INTO V_CNT
    FROM MST_CLIENT A,
      MST_CLIENT_FLACCT B
    WHERE A.CLIENT_CD =B.CLIENT_CD(+)
    AND A.CIFS IS NOT NULL
    AND B.CLIENT_CD  IS NULL
    AND A.CIFS        =P_CIFS;
    RETURN V_CNT;
    
  EXCEPTION
  WHEN NO_DATA_FOUND THEN
    NULL;
  WHEN OTHERS THEN
    RAISE;
  END F_CHECK_CIFS_RDI; 