create  FUNCTION F_GET_END_BAL_BANK(P_DATE DATE) RETURN NUMBER AS

V_AMT NUMBER;
V_BGN_BAL_DATE DATE;
VO_RANDOM_VALUE NUMBER(10,0);
VO_ERRCD NUMBER(5);
VO_ERRMSG VARCHAR(2);
BEGIN



BEGIN
SP_GENERATE_AGEING(
    P_DATE
    'ADP',
    '%',
    'ALL',
    VO_RANDOM_VALUE,
    VO_ERRCD ,
    VO_ERRMSG );
END;

	SELECT SUM(NVL(T0,0)) INTO V_AMT FROM RPT_AGEING WHERE RAND_VALUE=VO_RANDOM_VALUE AND USER_ID='ADP' AND T0>0;

	DELETE FROM RPT_AGEING WHERE RAND_VALUE=VO_RANDOM_VALUE AND USER_ID='ADP' ;

RETURN V_AMT;

END F_GET_END_BAL_BANK;