CREATE OR REPLACE FUNCTION F_GET_SETTDAYS(P_DATE DATE) RETURN NUMBER
AS

V_NUM MST_SYS_PARAM.DNUM1%TYPE;
BEGIN

SELECT DNUM1 INTO V_NUM FROM MST_SYS_PARAM WHERE PARAM_ID='SYSTEM' AND PARAM_CD1='SETTDAYS' AND  P_DATE BETWEEN DDATE1 AND DDATE2;

RETURN V_NUM;

END F_GET_SETTDAYS;