INSERT INTO MST_PARAMETER(PRM_CD_1,PRM_CD_2,PRM_DESC)VALUES('MUTASI','M','MUTASI');
INSERT INTO MST_PARAMETER(PRM_CD_1,PRM_CD_2,PRM_DESC)VALUES('MUTASI','I','INTEREST');
INSERT INTO MST_PARAMETER(PRM_CD_1,PRM_CD_2,PRM_DESC)VALUES('MUTASI','S','SETORAN');

COMMIT