
  CREATE TABLE "INSISTPRO_RPT"."R_RECON_STK_BAL_MAIN_ACCT_001" 
   (	"SUB_REK" VARCHAR2(14 BYTE), 
	"STK_CD" VARCHAR2(50 BYTE), 
	"SECU_THEO" NUMBER(18,0), 
	"SECU_ONH" NUMBER(18,0), 
	"SECU_OS_BUY" NUMBER(18,0), 
	"SECU_OS_SELL" NUMBER(18,0), 
	"CURR_THEO" NUMBER(18,0), 
	"CURR_ONH" NUMBER(18,0), 
	"PDATE_THEO" NUMBER(18,0), 
	"PDATE_ONH" NUMBER(18,0), 
	"KSEI" NUMBER(18,0), 
	"C_THEO" NUMBER(18,0), 
	"C_ONH" NUMBER(16,0), 
	"SELISIH" NUMBER(18,0), 
	"USER_ID" VARCHAR2(10 BYTE), 
	"GENERATE_DATE" DATE, 
	"RAND_VALUE" NUMBER(10,0), 
	"DT_BGN_DATE" DATE, 
	"DT_END_DATE" DATE
   )