
  CREATE TABLE "INSISTPRO_RPT"."R_T_STK_KSEI" 
   (	"IMPORT_DT" DATE, 
	"BAL_DT" DATE, 
	"SUB_REK" VARCHAR2(14 BYTE), 
	"STK_CD" VARCHAR2(20 BYTE), 
	"QTY" NUMBER(16,0), 
	"FREE" VARCHAR2(20 BYTE), 
	"USER_ID" VARCHAR2(10 BYTE), 
	"GENERATE_DATE" DATE, 
	"RAND_VALUE" NUMBER(10,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "INSISTPRO_RPT" ;
 
