create or replace PROCEDURE SP_APPROVE_VOUCHER_RDI_ALL(
     p_user_id    VARCHAR2 ,
    p_ip_address VARCHAR2 ,
    P_ERROR_CD OUT NUMBER ,
    p_error_msg OUT VARCHAR2 )
IS
  V_ERROR_MSG    VARCHAR2(200);
  V_ERROR_CD     NUMBER(10);
  V_ERR          EXCEPTION;
  v_cnt number:=0;
  CURSOR CSR_DATA IS
  SELECT UPDATE_DATE,UPDATE_SEQ,MENU_NAME FROM T_MANY_HEADER 
  WHERE MENU_NAME='GENERATE VOUCHER TRANSFER RDI'
  AND UPDATE_DATE>=TRUNC(SYSDATE) --UNCOMMENT JIKA TARO LIVE
  AND APPROVED_STATUS='E' 
  ORDER BY UPDATE_DATE, UPDATE_SEQ;

BEGIN

FOR REC IN CSR_DATA LOOP
  
    BEGIN
      SP_T_PAYRECH_APPROVE(REC.MENU_NAME, REC.UPDATE_DATE, REC.UPDATE_SEQ, p_user_id, p_ip_address, v_error_cd, V_ERROR_MSG);
    EXCEPTION
    WHEN OTHERS THEN
      v_error_cd  :=-10;
      v_error_msg :=SUBSTR('CALL SP_T_PAYRECH_APPROVE , UPDATE SEQ ='||REC.UPDATE_SEQ||' '||SQLERRM,1,4000);
      RAISE V_ERR;
    END;
    
    IF v_error_cd  <0 THEN
      v_error_cd  :=-15;
      v_error_msg :=SUBSTR('UPDATE SEQ ='||REC.UPDATE_SEQ||' '||V_ERROR_MSG,1,4000);
      RAISE V_ERR;
    END IF;  
    v_cnt :=v_cnt+1;
    
    END LOOP;
  
  P_ERROR_CD     := 1 ;
  P_ERROR_MSG    :=SUBSTR('Successfully approve '||V_CNT||' Voucher(s)',1,200);
  
EXCEPTION
WHEN V_ERR THEN
  ROLLBACK;
  P_ERROR_MSG := V_ERROR_MSG;
  P_ERROR_CD  := V_ERROR_CD;
WHEN OTHERS THEN
  P_ERROR_CD  := -1 ;
  P_ERROR_MSG := SUBSTR(SQLERRM(SQLCODE),1,200);
  RAISE;
END SP_APPROVE_VOUCHER_RDI_ALL;