create or replace PROCEDURE SP_BANK_MUTATION_UPDATE(
    VP_KODEAB T_BANK_MUTATION.KODEAB%TYPE,
    VP_NAMAAB T_BANK_MUTATION.NAMAAB%TYPE,
    VP_RDN T_BANK_MUTATION.RDN%TYPE,
    VP_SID T_BANK_MUTATION.SID%TYPE,
    VP_SRE T_BANK_MUTATION.SRE%TYPE,
    VP_NAMANASABAH T_BANK_MUTATION.NAMANASABAH%TYPE,
    VP_TANGGALEFEKTIF T_BANK_MUTATION.TANGGALEFEKTIF%TYPE,
    VP_TANGGALTIMESTAMP T_BANK_MUTATION.TANGGALTIMESTAMP%TYPE,
    VP_INSTRUCTIONFROM T_BANK_MUTATION.INSTRUCTIONFROM%TYPE,
    VP_COUNTERPARTACCOUNT T_BANK_MUTATION.COUNTERPARTACCOUNT%TYPE,
    VP_TYPEMUTASI T_BANK_MUTATION.TYPEMUTASI%TYPE,
    VP_TRANSACTIONTYPE T_BANK_MUTATION.TRANSACTIONTYPE%TYPE,
    VP_CURRENCY T_BANK_MUTATION.CURRENCY%TYPE,
    VP_BEGINNINGBALANCE T_BANK_MUTATION.BEGINNINGBALANCE%TYPE,
    VP_TRANSACTIONVALUE T_BANK_MUTATION.TRANSACTIONVALUE%TYPE,
    VP_CLOSINGBALANCE T_BANK_MUTATION.CLOSINGBALANCE%TYPE,
    VP_REMARK T_BANK_MUTATION.REMARK%TYPE,
    VP_BANKREFERENCE T_BANK_MUTATION.BANKREFERENCE%TYPE,
    VP_BANKID T_BANK_MUTATION.BANKID%TYPE,
    VP_IMPORTSEQ T_BANK_MUTATION.IMPORTSEQ%TYPE,
    VO_ERRCD OUT NUMBER,
    VO_ERRMSG OUT VARCHAR2 )
AS
  --2apr13 - tambah importseq = import sequence
  /* Dibuat oleh : Chandra Prasasta
  Tanggal  : 09 Mei 2012
  Menyimpan mutasi Bank BCA
  */
  vl_err EXCEPTION;
  v_cnt  NUMBER;
BEGIN

  v_cnt := 0;
  BEGIN
    SELECT COUNT(1)
    INTO v_cnt
    FROM T_BANK_MUTATION
    WHERE rdn           = VP_RDN
    AND tanggalefektif  = VP_TANGGALEFEKTIF
    AND BANKREFERENCE   = VP_BANKREFERENCE
    AND BANKID          = VP_BANKID
    AND TRANSACTIONTYPE = VP_TRANSACTIONTYPE;
  EXCEPTION
  WHEN NO_DATA_FOUND THEN
    v_cnt := 0;
  END;

  
  IF v_cnt = 0 THEN
    BEGIN
      INSERT
      INTO T_BANK_MUTATION
        (
          KODEAB, NAMAAB, RDN, SID, SRE, 
          NAMANASABAH, TANGGALEFEKTIF, TANGGALTIMESTAMP, INSTRUCTIONFROM, COUNTERPARTACCOUNT, 
          TYPEMUTASI, TRANSACTIONTYPE, CURRENCY, BEGINNINGBALANCE, TRANSACTIONVALUE, 
          CLOSINGBALANCE, REMARK,BANKREFERENCE, BANKID, IMPORTSEQ, IMPORTDATE
        )
        VALUES
        (
          VP_KODEAB, VP_NAMAAB, VP_RDN, VP_SID, VP_SRE,
          VP_NAMANASABAH, VP_TANGGALEFEKTIF, VP_TANGGALTIMESTAMP, VP_INSTRUCTIONFROM, VP_COUNTERPARTACCOUNT,
          VP_TYPEMUTASI, F_CLEAN(VP_TRANSACTIONTYPE), VP_CURRENCY, VP_BEGINNINGBALANCE, VP_TRANSACTIONVALUE,
          VP_CLOSINGBALANCE, VP_REMARK, VP_BANKREFERENCE, VP_BANKID, vp_IMPORTSEQ, SYSDATE
        );
    EXCEPTION
    WHEN OTHERS THEN
      VO_ERRCD  := -1;
      VO_ERRMSG := SUBSTR(SQLERRM(SQLCODE),1,200);
      RAISE vl_err;
    END;
  END IF;
  
  VO_ERRCD := 1;
  
  --COMMIT;
EXCEPTION
WHEN vl_err THEN
  ROLLBACK;
END Sp_Bank_Mutation_Update;