create or replace PROCEDURE SP_CANCEL_TRADE_CONF(
    P_TRX_DATE   DATE,
    P_TRX_SEQ_NO NUMBER,
    P_IM_CODE VARCHAR2,
    P_ERROR_CODE OUT NUMBER,
    P_ERROR_MSG OUT VARCHAR2)
IS
  V_ERR        EXCEPTION;
  V_ERROR_CODE NUMBER(5);
  V_ERROR_MSG  VARCHAR2(200);
  
BEGIN

  BEGIN
    UPDATE TC_DOWNLOAD
    SET TRANSACTION_STATUS='CANC'
    WHERE TRADE_DATE      =P_TRX_DATE
    AND TRX_SEQ_NO        =P_TRX_SEQ_NO
    AND IM_CODE = P_IM_CODE;
  EXCEPTION
  WHEN NO_DATA_FOUND THEN
    NULL;
  WHEN OTHERS THEN
    V_ERROR_CODE:=-20;
    V_ERROR_MSG :=SUBSTR('UPDATE TC_DOWNLOAD WHERE TRADE DATE '||TO_CHAR(P_TRX_DATE,'DD-MM-YYYY')||' '||P_TRX_SEQ_NO ||' '||SQLERRM,1,200);
  END;
  P_ERROR_CODE :=1;
  P_ERROR_MSG  :='';
EXCEPTION
WHEN V_ERR THEN
  ROLLBACK;
  P_ERROR_CODE :=V_ERROR_CODE;
  P_ERROR_MSG  :=V_ERROR_MSG;
WHEN OTHERS THEN
  ROLLBACK;
  P_ERROR_CODE :=-1;
  P_ERROR_MSG  := SUBSTR(SQLERRM,1,200);
  RAISE;
END SP_CANCEL_TRADE_CONF;