CREATE OR REPLACE PROCEDURE SP_CANCEL_WORKSHEET_INT(
    p_bgn_date IN T_INTEREST.int_dt%TYPE,
    p_end_date IN T_INTEREST.int_dt%TYPE,
    p_client_cd mst_client.client_cd%type,
    p_user_id T_MANY_HEADER.USER_ID%TYPE,
    P_ERROR_CODE OUT NUMBER,
    P_ERROR_MSG OUT VARCHAR2)
IS
  V_ERROR_CODE NUMBER(5);
  V_ERROR_MSG  VARCHAR2(200);
  V_ERR        EXCEPTION;
BEGIN

  BEGIN
    UPDATE T_INTEREST
    SET POST_FLG='N'
    WHERE INT_DT BETWEEN p_bgn_date AND p_end_date
    AND CLIENT_CD = p_client_cd;
  EXCEPTION
  WHEN OTHERS THEN
    V_ERROR_CODE := -10;
    V_ERROR_MSG  :=SUBSTR('UPDATE POST_FLG T_INTEREST '||p_client_cd||' '|| SQLERRM,1,200);
    RAISE V_ERR;
  END;
  
  P_ERROR_CODE:=1;
  P_ERROR_MSG :='';
  
EXCEPTION
WHEN V_ERR THEN
  ROLLBACK;
  P_ERROR_CODE := V_ERROR_CODE;
  P_ERROR_MSG  := V_ERROR_MSG;
WHEN OTHERS THEN
  P_ERROR_CODE := -1 ;
  P_ERROR_MSG  := SUBSTR(SQLERRM(SQLCODE),1,200);
  RAISE;
END SP_CANCEL_WORKSHEET_INT;