create or replace PROCEDURE SP_GEN_CSV_IM(
    P_TRX_DATE DATE,
    P_IM_CODE  VARCHAR2,
    P_USER_ID  VARCHAR2,
    P_RAND_VALUE OUT NUMBER,
    P_ERROR_CODE OUT NUMBER,
    P_ERROR_MSG OUT VARCHAR2)
IS
  v_random_value NUMBER;
BEGIN
  v_random_value := ABS(dbms_random.random);
  --SINARMAS
  IF P_IM_CODE ='DH002' THEN
    BEGIN
      DELETE FROM IM_FILE_CSV_SINARMAS WHERE USER_ID =P_USER_ID;
    EXCEPTION
    WHEN OTHERS THEN
      P_ERROR_CODE := -10;
      P_ERROR_MSG  :=SUBSTR('INSERT INTO IM_FILE_CSV '||SQLERRM,1,200);
      RAISE;
    END;
    BEGIN
      INSERT
      INTO IM_FILE_CSV_SINARMAS
        (
          FUNDID ,TRANSREFNO ,TRANSACTIONDATE ,SETTLEMENTDATE ,BROKERCODE ,
          STOCKCODE , TRANSACTIONTYPE ,FLAGNETTING ,VOLUME , PRICE ,PROCEED ,
          LEVY ,KPEI ,VAT ,WHT ,CAPITALGAINTAX ,
          BROKERFEE , NETAMOUNT, CRE_DT,USER_ID,RAND_VALUE
        )
      SELECT FUND_CODE fundID , NULL TransRefNo ,TRX_DATE AS TransactionDate ,TRX_DUE_DATE SettlementDate ,BROKER_CD BrokerCode ,
      STK_CD StockCode , DECODE(GL_CODE,'TBE','B','S') TransactionType ,0 FlagNetting ,QTY Volume , PRICE Price ,CURR_VALUE Proceed ,
      (0.033/100*S.CURR_VALUE)LEVY ,(0.01/100 * CURR_VALUE) KPEI ,VAT ,WITHHOLDING_PPH WHT ,DECODE(GL_CODE,'TJE',(0.1/100*CURR_VALUE),0) CapitalGainTax ,
      NET_COMMISION_VALUE BrokerFee , DECODE(GL_CODE,'TBE',(S.NET_VALUE-S.WITHHOLDING_PPH),(S.NET_VALUE+S.WITHHOLDING_PPH)) NetAmount, SYSDATE,P_USER_ID, v_random_value
      FROM stock_transaction S, MST_IM M, MST_FUND_CLIENT C
      WHERE M.IM_CODE = C.IM_CODE
      AND C.CLIENT_CD = S.SL_CODE
      AND S.TRX_STATUS='A'
      AND M.IM_CODE   = P_IM_CODE
      AND TRX_DATE    = P_TRX_DATE;
    EXCEPTION
    WHEN OTHERS THEN
      P_ERROR_CODE := -20;
      P_ERROR_MSG  :=SUBSTR('INSERT INTO IM_FILE_CSV_SINARMAS '||SQLERRM,1,200);
      RAISE;
    END;
  END IF;
  IF P_IM_CODE ='YJ002' THEN--LIM
    BEGIN
      DELETE FROM IM_FILE_CSV_LIM WHERE USER_ID =P_USER_ID;
    EXCEPTION
    WHEN OTHERS THEN
      P_ERROR_CODE := -30;
      P_ERROR_MSG  :=SUBSTR('DELETE IM_FILE_CSV_LIM '|| SQLERRM,1,200);
      RAISE;
    END;
    BEGIN
      INSERT
      INTO IM_FILE_CSV_LIM
        (
          TRX_STS ,TA_REF_ID ,TA_REF_NO ,TRX_DATE ,TRX_DUE_DATE ,IM_CODE ,BROKER_CD ,FUND_CODE ,
          STK_CD ,BUY_SELL ,PRICE ,QTY ,CURR_VALUE ,NET_COMMISION_VALUE ,SALES_TAX ,
          LEVY ,VAT ,OTHER_CHARGES ,GROSS_SETTLEMENT_AMT ,WITHHOLDING_PPH ,
          NET_VALUE ,SETTLEMENT_TYPE ,REMARKS ,CANCEL_REASON ,CRE_DT ,USER_ID ,RAND_VALUE
        )
      SELECT 'NEWN' TRX_STS, '-' TA_REF_ID, F_GET_TA_REF(TRX_DATE) TA_REF_NO, TRX_DATE, TRX_DUE_DATE, M.IM_CODE, BROKER_CD, FUND_CODE, 
      STK_CD, DECODE(GL_CODE,'TBE',1,0)BUY_SELL, PRICE, QTY, CURR_VALUE, NET_COMMISION_VALUE, DECODE(S.GL_CODE,'TJE',(0.1/100 * CURR_VALUE),0)SALES_TAX, 
      LEVY, VAT, NULL OTHER_CHARGES,S.NET_VALUE GROSS_SETTLEMENT_AMT, WITHHOLDING_PPH, 
      DECODE(GL_CODE,'TBE',(NET_VALUE-WITHHOLDING_PPH),(NET_VALUE+WITHHOLDING_PPH))NET_SETTLEMENT_AMOUNT, 
      DECODE(GL_CODE,'TJE','1','2')SETTLEMENT_TYPE, '-' REMARKS, '-' CANCEL_REASON,SYSDATE, P_USER_ID,v_random_value
      FROM stock_transaction S, MST_IM M, MST_FUND_CLIENT C
      WHERE M.IM_CODE = C.IM_CODE
      AND C.CLIENT_CD = S.SL_CODE
      AND S.TRX_STATUS='A'
      AND M.IM_CODE   = P_IM_CODE
      AND TRX_DATE    = P_TRX_DATE;
    EXCEPTION
    WHEN OTHERS THEN
      P_ERROR_CODE := -40;
      P_ERROR_MSG  :=SUBSTR('INSERT INTO IM_FILE_CSV_LIM '||SQLERRM,1,200);
      RAISE;
    END;
  END IF;
  --SCHRODER
  IF P_IM_CODE = 'SCH02' THEN
    BEGIN
      DELETE FROM IM_FILE_CSV_SCH WHERE USER_ID =P_USER_ID;
    EXCEPTION
    WHEN OTHERS THEN
      P_ERROR_CODE := -50;
      P_ERROR_MSG  :=SUBSTR('DELETE IM_FILE_CSV_SCH '|| SQLERRM,1,200);
      RAISE;
    END;
    BEGIN
      INSERT
      INTO IM_FILE_CSV_SCH
        (
          PORTFOLIO_ID ,TRANS_NO ,B_S ,TRX_DATE ,TRX_DUE_DATE ,STK_CD ,ISIN_CODE ,
          QC ,QTY ,PRICE ,CURR_VALUE ,NET_COMMISION_VALUE ,LEVY ,VAT ,
          SALES_TAX ,OTHER_CHARGES ,TOTAL ,WITHHOLDING_PPH ,
          VAT2 ,NET_VALUE ,BROKER_CD ,
          NAMA_PRSH ,CRE_DT ,USER_ID ,RAND_VALUE
        )
      SELECT C.PORTFOLIO_ID, null TRANS_NO, DECODE(T.GL_CODE,'TBE','B','S')B_S, T.TRX_DATE, T.TRX_DUE_DATE, T.STK_CD, S.ISIN_CODE,
      'IDR' AS QC, T.QTY, T.PRICE, T.CURR_VALUE, T.NET_COMMISION_VALUE, T.LEVY, T.VAT, 
      DECODE(T.GL_CODE,'TJE',(0.1/100*T.CURR_VALUE),0) AS SALES_TAX, null OTHER_CHARGES,  T.NET_VALUE TOTAL, T.WITHHOLDING_PPH, 
      null  VAT2, DECODE(T.GL_CODE,'TJE',(T.NET_VALUE+T.WITHHOLDING_PPH),(T.NET_VALUE-T.WITHHOLDING_PPH)) NET_SETTLEMENT_AMOUNT, T.BROKER_CD,
      P.NAMA_PRSH, SYSDATE CRE_DT, P_USER_ID, v_random_value
      FROM STOCK_TRANSACTION T, MST_FUND_CLIENT C, MST_COUNTER S, MST_COMPANY P, MST_IM M
      WHERE T.SL_CODE = C.CLIENT_CD
      AND T.STK_CD    = S.STK_CD
      AND C.IM_CODE = M.IM_CODE
      AND T.TRX_STATUS='A'
      AND M.IM_CODE = P_IM_CODE
      AND T.TRX_DATE  = P_TRX_DATE;
    EXCEPTION
    WHEN OTHERS THEN
      P_ERROR_CODE := -60;
      P_ERROR_MSG  :=SUBSTR('INSERT INTO IM_FILE_CSV_SCH '||SQLERRM,1,200);
      RAISE;
    END;
  END IF;
  ---SYAILENDRA
  IF P_IM_CODE='SYA02' THEN
   BEGIN
      DELETE FROM IM_FILE_CSV_SYA WHERE USER_ID =P_USER_ID;
    EXCEPTION
    WHEN OTHERS THEN
      P_ERROR_CODE := -70;
      P_ERROR_MSG  :=SUBSTR('DELETE IM_FILE_CSV_SYA '|| SQLERRM,1,200);
      RAISE;
    END;
    
  BEGIN
  INSERT INTO IM_FILE_CSV_SYA(BRANCH_CODE,TRX_DATE,TRX_DUE_DATE,SL_CODE,CLIENT_NAME,DEF_ADDR_1,DEF_ADDR_2,DEF_ADDR_3,
    POST_CD,PHONE_NUM,FAX_NUM,STK_CD,L_F,LOT,QTY,PRICE,B_S,
    TRX_MRKT_TYPE,TOTAL_VALUE,COMMISSION,VAT,LEVY,
    SALES_TAX,WITHHOLDING_PPH,TOTAL_NET,
    NPWP_NO,PKP,REM_NAME,CRE_DT,USER_ID,RAND_VALUE)
    SELECT trim(m.branch_code)branch_code, T.TRX_DATE, T.TRX_DUE_DATE, T.SL_CODE, M.CLIENT_NAME, M.DEF_ADDR_1, M.DEF_ADDR_2, M.DEF_ADDR_3,
     M.POST_CD,M.PHONE_NUM, M.FAX_NUM, T.STK_CD, 'L' L_F, T.LOT, T.QTY, T.PRICE,DECODE(T.GL_CODE,'TBE','BUY','SELL') B_S,
      T.TRX_MRKT_TYPE, ROUND(T.CURR_VALUE) TOTAL_VALUE, ROUND(T.NET_COMMISION_VALUE) COMMISSION, ROUND(VAT)VAT, ROUND(LEVY) LEVY ,
      DECODE(GL_CODE,'TJE',ROUND(0.1/100*T.CURR_VALUE),0) SALES_TAX, ROUND(T.WITHHOLDING_PPH) WITHHOLDING_PPH,
       DECODE(GL_CODE,'TBE',ROUND(T.NET_VALUE - T.WITHHOLDING_PPH),ROUND(T.NET_VALUE + T.WITHHOLDING_PPH) )TOTAL_NET, 
       M.NPWP_NO, M.NPWP_NO PKP,S.REM_NAME, SYSDATE CRE_DT, P_USER_ID,v_random_value
    FROM mst_client m,stock_transaction t, MST_SALES S, MST_IM IM, MST_FUND_CLIENT C
    WHERE m.client_cd  =t.sl_code
    AND M.REM_CD       =S.REM_CD
    AND S.APPROVED_STAT='A'
    AND T.TRX_STATUS   ='A'
    AND M.APPROVED_STAT='A'
    AND IM.IM_CODE     =C.IM_CODE
    AND M.CLIENT_CD    = C.CLIENT_CD
    AND T.TRX_DATE     = P_TRX_DATE
    AND IM.IM_CODE     = P_IM_CODE;
    EXCEPTION
    WHEN OTHERS THEN
      P_ERROR_CODE := -80;
      P_ERROR_MSG  :=SUBSTR('INSERT INTO IM_FILE_CSV_SYA '||SQLERRM,1,200);
      RAISE;
    END;
  END IF;

  COMMIT;
  P_RAND_VALUE :=v_random_value;
  P_ERROR_CODE :=1;
  P_ERROR_MSG  :='';
EXCEPTION
WHEN OTHERS THEN
  ROLLBACK;
  P_ERROR_CODE :=-1;
  P_ERROR_MSG  := SUBSTR(SQLERRM,1,200);
END SP_GEN_CSV_IM;