create or replace PROCEDURE SP_INSERT_FUND_H2H_BCA(P_USER_ID VARCHAR2, P_IP_ADDRESS VARCHAR2, P_ERROR_CODE OUT NUMBER, P_ERROR_MSG OUT VARCHAR2) IS

CURSOR CSR_DATA IS
 SELECT EXTERNAL_REF,ACCT_NUM
    FROM IPNEXTG.t_client_acct_statement A, IPNEXTG.MST_RDI_TRX_TYPE R, (
        SELECT REPLACE(REPLACE(BANK_ACCT_CD,'-',''),'.','') PE_BANK_ACCT
        FROM IPNEXTG.MST_BANK_ACCT
        WHERE BANK_ACCT_CD <> 'X'
      )
      B
    WHERE TRX_DATE    >='31MAR2017'
    AND A.TRX_TYPE    = R.RDI_TRX_TYPE
    AND TRX_TYPE IN('NINT','NTAX')
    AND A.TRX_CD      =R.DB_CR_FLG
    AND A.ACCT_DEBIT  = B.PE_BANK_ACCT(+)
    AND PE_BANK_ACCT IS NULL;
	
	V_ERR EXCEPTION;
	V_ERROR_CODE NUMBER;
	V_ERROR_MSG VARCHAR2(200);
	V_CNT NUMBER:=0;
	
	BEGIN
	
	FOR REC IN CSR_DATA LOOP
	BEGIN
	 SP_FUND_AUTO_BCA(
					REC.EXTERNAL_REF,
					REC.ACCT_NUM,
					P_USER_ID,
					P_IP_ADDRESS,
					V_ERROR_CODE,
					V_ERROR_MSG);
		
		EXCEPTION
		WHEN OTHERS THEN
		V_ERROR_CODE :=-10;
		V_ERROR_MSG :=SUBSTR('CALL SP_FUND_AUTO_BCA'||SQLERRM,1,200);
		RAISE V_ERR;
		END;
		IF V_ERROR_CODE<0 THEN
			V_ERROR_CODE :=-20;
			V_ERROR_MSG := SUBSTR('SP_FUND_AUTO_BCA'||V_ERROR_MSG,1,200);
			RAISE V_ERR;
		END IF;
		
		V_CNT :=V_CNT+1;
	END LOOP;
	
	P_ERROR_CODE :=1;
	P_ERROR_MSG:= 'SUCCESSFULLY MAKE '||V_CNT ||' JOURNAL(S)';
	
	
	EXCEPTION
	WHEN V_ERR THEN
	ROLLBACK;
	P_ERROR_CODE := V_ERROR_CODE;
	P_ERROR_MSG := V_ERROR_MSG;
	WHEN OTHERS THEN
		ROLLBACK;
		P_ERROR_CODE :=-1;
		P_ERROR_MSG:=SUBSTR(SQLERRM,1,200);
	END SP_INSERT_FUND_H2H_BCA;