CREATE OR REPLACE PROCEDURE SP_INSERT_DAILY_OTC_JUR(
    P_JUR_DATE DATE,
    P_DOC_NUM T_DAILY_OTC_JUR.DOC_NUM%TYPE,
    P_CLIENT_CD T_DAILY_OTC_JUR.CLIENT_CD%TYPE,
    P_SUM_OTC T_DAILY_OTC_JUR.SUM_OTC%TYPE,
    P_TIDAK_DIJURNAL T_DAILY_OTC_JUR.TIDAK_DIJURNAL%TYPE,
    P_XN_DOC_NUM T_DAILY_OTC_JUR.XN_DOC_NUM%TYPE,
    P_USER_ID T_DAILY_OTC_JUR.USER_ID%TYPE,
    P_ERROR_CODE OUT NUMBER,
    P_ERROR_MSG OUT VARCHAR2)
IS
  V_ERR        EXCEPTION;
  V_ERROR_CODE NUMBER(5);
  V_ERROR_MSG  VARCHAR2(200);
BEGIN

  BEGIN
    INSERT
    INTO T_DAILY_OTC_JUR
      (
        JUR_DATE, DOC_NUM, CLIENT_CD, SUM_OTC, TIDAK_DIJURNAL, XN_DOC_NUM, USER_ID, CRE_DT
      )
      VALUES
      (
        P_JUR_DATE, P_DOC_NUM,P_CLIENT_CD,P_SUM_OTC,P_TIDAK_DIJURNAL,P_XN_DOC_NUM,P_USER_ID,SYSDATE
      );
  EXCEPTION
  WHEN OTHERS THEN
    V_ERROR_CODE :=-15;
    V_ERROR_MSG  :=SUBSTR('INSERT INTO T_DAILY_OTC_JUR '||SQLERRM,1,200);
    RAISE V_ERR;
  END;

  P_ERROR_CODE:=1;
  P_ERROR_MSG:='';
  
EXCEPTION
WHEN V_ERR THEN
  ROLLBACK;
  P_ERROR_CODE :=V_ERROR_CODE;
  P_ERROR_MSG  :=V_ERROR_MSG;
WHEN OTHERS THEN
  ROLLBACK;
  P_ERROR_CODE :=-1;
  P_ERROR_MSG  :=SUBSTR(SQLERRM,1,200);
  RAISE;
END SP_INSERT_DAILY_OTC_JUR;