CREATE OR REPLACE 
PROCEDURE SP_IPO_ENTRY_UPD(

							P_ERROR_CODE OUT NUMBER,
							P_ERROR_MSG OUT VARCHAR2
							)
IS
V_ERROR_CODE NUMBER;
V_ERROR_MSG VARCHAR2(200);
BEGIN











	P_ERROR_CODE := 1;
	P_ERROR_MSG := '';

EXCEPTION
    WHEN NO_DATA_FOUND THEN
		NULL;
	WHEN V_ERR THEN
		P_ERROR_CODE := V_ERROR_CODE;
		P_ERROR_MSG :=  V_ERROR_MSG;
		ROLLBACK;
    WHEN OTHERS THEN
       -- CONSIDER LOGGING THE ERROR AND THEN RE-RAISE
	    ROLLBACK;
		P_ERROR_CODE := -1;
		P_ERROR_MSG := SUBSTR(SQLERRM,1,200);
		RAISE;

END  SP_IPO_ENTRY_UPD;