create or replace PROCEDURE SPR_SURAT_PPH_NSB(
    P_TAHUN NUMBER,
    P_CIFS mst_CLIENT.CIFS%TYPE,
    P_USER_ID       VARCHAR2,
    P_GENERATE_DATE DATE,
    P_RANDOM_VALUE OUT NUMBER,
    P_ERROR_CD OUT NUMBER,
    P_ERROR_MSG OUT VARCHAR2 )
IS
  V_ERROR_MSG    VARCHAR2(200);
  V_ERROR_CD     NUMBER(10);
  v_random_value NUMBER(10);
  V_ERR          EXCEPTION;
  V_BGN_DATE DATE;
  V_END_DATE DATE;
  V_CIFS MST_CLIENT.CIFS%TYPE;
BEGIN
  
  v_random_value := ABS(dbms_random.random);
  
  BEGIN
    SP_RPT_REMOVE_RAND('R_SURAT_PPH_NSB',V_RANDOM_VALUE,V_ERROR_MSG,V_ERROR_CD);
  EXCEPTION
  WHEN OTHERS THEN
    V_ERROR_CD  := -10;
    V_ERROR_MSG := SUBSTR('SP_RPT_REMOVE_RAND '||V_ERROR_MSG||SQLERRM(SQLCODE),1,200);
    RAISE V_err;
  END;
  
  IF V_ERROR_CD  <0 THEN
    V_ERROR_CD  := -20;
    V_ERROR_MSG := SUBSTR('SP_RPT_REMOVE_RAND'||V_ERROR_MSG,1,200);
    RAISE V_ERR;
  END IF;
  
  V_BGN_DATE :=TO_DATE('0101'||P_TAHUN,'DDMMYYYY');
  V_END_DATE :=TO_DATE('3112'||P_TAHUN,'DDMMYYYY');

  BEGIN
  INSERT INTO R_SURAT_PPH_NSB(TAHUN,CIFS,CLIENT_TITLE,CLIENT_NAME,PPH_AMT,TERBILANG_IND,USER_ID,RAND_VALUE,GENERATE_DATE)
  select P_TAHUN, MAX(M.CIFS)CIFS,INITCAP(MAX(M.CLIENT_TITLE))CLIENT_TITLE,INITCAP(MAX(M.CLIENT_NAME))CLIENT_NAME,ROUND(SUM(pph),0)PPH, 
  lower(F_TERBILANG_2(ROUND(SUM(PPH),0)))TERBILANG,P_USER_ID,V_RANDOM_VALUE,P_GENERATE_DATE
   from mst_CLIENT M ,t_contracts T 
  where M.CLIENT_CD=T.CLIENT_CD
  AND contr_stat<>'C'
  AND SUBSTR(T.CONTR_NUM,5,1)='J'
  AND CONTR_DT BETWEEN V_BGN_DATE AND V_END_DATE
  AND M.CIFS=P_CIFS;
  EXCEPTION
  WHEN OTHERS THEN
    V_ERROR_CD :=-30;
    V_ERROR_MSG :=SUBSTR('INSERT INTO R_SURAT_PPH_NSB '||SQLERRM,1,200);
    RAISE V_ERR; 
  END;
   
   --jika tidak ada transaksi keluar pesar error
   BEGIN
   SELECT CIFS INTO V_CIFS FROM R_SURAT_PPH_NSB WHERE RAND_VALUE=V_RANDOM_VALUE AND USER_ID=P_USER_ID;
   EXCEPTION
   WHEN OTHERS THEN
     V_ERROR_CD :=-25;
    V_ERROR_MSG :=SUBSTR('SELECT COUNT  R_SURAT_PPH_NSB'||SQLERRM,1,200);
    RAISE V_ERR; 
   END;
   
   IF V_CIFS IS NULL THEN
      V_ERROR_CD :=-25;
      V_ERROR_MSG :='Transaksi untuk CIFS '||P_CIFS||' pada tahun '||P_TAHUN|| ' tidak ditemukan';
      RAISE V_ERR; 
   END IF;
   
  P_RANDOM_VALUE :=V_RANDOM_VALUE;
  P_ERROR_CD     := 1 ;
  P_ERROR_MSG    := '';
  
EXCEPTION
WHEN V_ERR THEN
  ROLLBACK;
  P_ERROR_MSG := V_ERROR_MSG;
  P_ERROR_CD  := V_ERROR_CD;
WHEN OTHERS THEN
  P_ERROR_CD  := -1 ;
  P_ERROR_MSG := SUBSTR(SQLERRM(SQLCODE),1,200);
  RAISE;
END SPR_SURAT_PPH_NSB;