create or replace 
PROCEDURE SPR_FIXED_ASSET(
    P_END_DATE DATE,
    P_BRANCH_CD MST_BRANCH.BRCH_CD%TYPE,
    P_USER_ID       VARCHAR2,
    P_GENERATE_DATE DATE,
    P_RANDOM_VALUE OUT NUMBER,
    P_ERROR_CD OUT NUMBER,
    P_ERROR_MSG OUT VARCHAR2 )
IS
  V_ERROR_MSG    VARCHAR2(200);
  V_ERROR_CD     NUMBER(10);
  V_RANDOM_VALUE NUMBER(10);
  V_ERR          EXCEPTION;
  V_DATE_LAST_YEAR DATE;
  V_BGN_DATE_YR DATE;
BEGIN
  V_RANDOM_VALUE := ABS(DBMS_RANDOM.RANDOM);
  
  BEGIN
    SP_RPT_REMOVE_RAND('R_FIXED_ASSET',V_RANDOM_VALUE,V_ERROR_MSG,V_ERROR_CD);
  EXCEPTION
  WHEN OTHERS THEN
    V_ERROR_CD  := -10;
    V_ERROR_MSG := SUBSTR('SP_RPT_REMOVE_RAND '||V_ERROR_MSG||SQLERRM(SQLCODE),1,200);
    RAISE V_err;
  END;
  
  IF V_ERROR_CD  <0 THEN
    V_ERROR_CD  := -20;
    V_ERROR_MSG := SUBSTR('SP_RPT_REMOVE_RAND'||V_ERROR_MSG,1,200);
    RAISE V_ERR;
  END IF;

  
V_DATE_LAST_YEAR :=TO_DATE('3112'||TO_NUMBER(TO_CHAR(P_END_DATE,'YYYY'))-1,'DDMMYYYY');
V_BGN_DATE_YR := TO_DATE('0101'||TO_CHAR(P_END_DATE,'YYYY'),'DDMMYYYY');

  BEGIN
    INSERT
    INTO R_FIXED_ASSET
      (
        BRANCH_CD ,
        ASSET_CD ,
        ASSET_TYPE ,
        ASSET_DESC ,
        PURCH_DT ,
        PURCH_PRICE ,
        AGE ,
        ACCUM_LAST_YR ,
        DEPR_MON ,
        DEPR_AMT ,
        DEPR_ACCUM ,
        AGE_ACCUM ,
        BRANCH_NAME ,
        TYPE_NAME ,
        ASSET_PREFIX ,
        END_DATE ,
        USER_ID ,
        RAND_VALUE ,
        GENERATE_DATE,
        DATE_LAST_YEAR,
        BGN_DATE_YR
      )
    SELECT M.BRANCH_CD,
      M.ASSET_CD,
      M.ASSET_TYPE,
      M.ASSET_DESC,
      M.PURCH_DT,
      M.PURCH_PRICE,
      M.AGE,
      M.ACCUM_LAST_YR,
      T.DEPR_MON,
      T.DEPR_AMT,
      T.DEPR_ACCUM,
      T.AGE_ACCUM,
      B.BRCH_NAME BRANCH_NAME,
      P2.PRM_DESC TYPE_NAME,
      SUBSTR(M.ASSET_CD,1,1) ASSET_PREFIX ,
      P_END_DATE,
      P_USER_ID,
      V_RANDOM_VALUE,
      P_GENERATE_DATE,
      V_DATE_LAST_YEAR,
      V_BGN_DATE_YR
    FROM MST_FIXED_ASSET M,
      T_MON_DEPR T,
      MST_BRANCH B,
      MST_PARAMETER P2
    WHERE M.ASSET_STAT = 'ACTIVE'
    AND M.ASSET_CD     = T.ASSET_CD
    AND T.DEPR_MON     = TO_CHAR(P_END_DATE,'MMYY')
    AND (B.BRCH_CD      = P_BRANCH_CD OR P_BRANCH_CD='%')
    AND B.BRCH_CD      = M.BRANCH_CD
    AND P2.PRM_CD_1    = 'FASSET'
    AND P2.PRM_CD_2    = M.ASSET_TYPE;
  EXCEPTION
  WHEN OTHERS THEN
    V_ERROR_CD  := -50;
    V_ERROR_MSG := SUBSTR('INSERT R_FIXED_ASSET '||V_ERROR_MSG||SQLERRM(SQLCODE),1,200);
    RAISE V_err;
  END;
  
  P_RANDOM_VALUE :=V_RANDOM_VALUE;
  P_ERROR_CD     := 1 ;
  P_ERROR_MSG    := '';
  
EXCEPTION
WHEN V_ERR THEN
  ROLLBACK;
  P_ERROR_MSG := V_ERROR_MSG;
  P_ERROR_CD  := V_ERROR_CD;
WHEN OTHERS THEN
  P_ERROR_CD  := -1 ;
  P_ERROR_MSG := SUBSTR(SQLERRM(SQLCODE),1,200);
  RAISE;
END SPR_FIXED_ASSET;