select A.*, M.ACCT_NAME from( SELECT NULL SORTK,
					(SELECT to_date(FIELD_VALUE,'yyyy/mm/dd hh24:mi:ss') FROM T_MANY_DETAIL DA 
					        WHERE DA.TABLE_NAME = 'T_ACCOUNT_LEDGER' 
					        AND DA.UPDATE_DATE = DD.UPDATE_DATE
					        AND DA.UPDATE_SEQ = DD.UPDATE_SEQ
					        AND DA.FIELD_NAME = 'DOC_DATE'
					        AND DA.RECORD_SEQ = DD.RECORD_SEQ)DOC_DATE, 
          (SELECT FIELD_VALUE FROM T_MANY_DETAIL DA 
					        WHERE DA.TABLE_NAME = 'T_ACCOUNT_LEDGER' 
					        AND DA.UPDATE_DATE = DD.UPDATE_DATE
					        AND DA.UPDATE_SEQ = DD.UPDATE_SEQ
					        AND DA.FIELD_NAME = 'XN_DOC_NUM'
					        AND DA.RECORD_SEQ = DD.RECORD_SEQ) XN_DOC_NUM,
           (SELECT FIELD_VALUE FROM T_MANY_DETAIL DA 
					        WHERE DA.TABLE_NAME = 'T_ACCOUNT_LEDGER' 
					        AND DA.UPDATE_DATE = DD.UPDATE_DATE
					        AND DA.UPDATE_SEQ = DD.UPDATE_SEQ
					        AND DA.FIELD_NAME = 'TAL_ID'
					        AND DA.RECORD_SEQ = DD.RECORD_SEQ) TAL_ID,
           (SELECT FIELD_VALUE FROM T_MANY_DETAIL DA 
					        WHERE DA.TABLE_NAME = 'T_ACCOUNT_LEDGER' 
					        AND DA.UPDATE_DATE = DD.UPDATE_DATE
					        AND DA.UPDATE_SEQ = DD.UPDATE_SEQ
					        AND DA.FIELD_NAME = 'GL_ACCT_CD'
					        AND DA.RECORD_SEQ = DD.RECORD_SEQ) GL_ACCT_CD,
          (SELECT FIELD_VALUE FROM T_MANY_DETAIL DA 
					        WHERE DA.TABLE_NAME = 'T_ACCOUNT_LEDGER' 
					        AND DA.UPDATE_DATE = DD.UPDATE_DATE
					        AND DA.UPDATE_SEQ = DD.UPDATE_SEQ
					        AND DA.FIELD_NAME = 'SL_ACCT_CD'
					        AND DA.RECORD_SEQ = DD.RECORD_SEQ) SL_ACCT_CD,
            (SELECT FIELD_VALUE FROM T_MANY_DETAIL DA 
					        WHERE DA.TABLE_NAME = 'T_ACCOUNT_LEDGER' 
					        AND DA.UPDATE_DATE = DD.UPDATE_DATE
					        AND DA.UPDATE_SEQ = DD.UPDATE_SEQ
					        AND DA.FIELD_NAME = 'DB_CR_FLG'
					        AND DA.RECORD_SEQ = DD.RECORD_SEQ) DB_CR_FLG,
           (SELECT FIELD_VALUE FROM T_MANY_DETAIL DA 
					        WHERE DA.TABLE_NAME = 'T_ACCOUNT_LEDGER' 
					        AND DA.UPDATE_DATE = DD.UPDATE_DATE
					        AND DA.UPDATE_SEQ = DD.UPDATE_SEQ
					        AND DA.FIELD_NAME = 'CURR_VAL'
					        AND DA.RECORD_SEQ = DD.RECORD_SEQ) CURR_VAL,
          (SELECT FIELD_VALUE FROM T_MANY_DETAIL DA 
					        WHERE DA.TABLE_NAME = 'T_ACCOUNT_LEDGER' 
					        AND DA.UPDATE_DATE = DD.UPDATE_DATE
					        AND DA.UPDATE_SEQ = DD.UPDATE_SEQ
					        AND DA.FIELD_NAME = 'LEDGER_NAR'
					        AND DA.RECORD_SEQ = DD.RECORD_SEQ) LEDGER_NAR,
          (SELECT FIELD_VALUE FROM T_MANY_DETAIL DA 
					        WHERE DA.TABLE_NAME = 'T_ACCOUNT_LEDGER' 
					        AND DA.UPDATE_DATE = DD.UPDATE_DATE
					        AND DA.UPDATE_SEQ = DD.UPDATE_SEQ
					        AND DA.FIELD_NAME = 'USER_ID'
					        AND DA.RECORD_SEQ = DD.RECORD_SEQ) USER_ID,
          (SELECT FIELD_VALUE FROM T_MANY_DETAIL DA 
					        WHERE DA.TABLE_NAME = 'T_ACCOUNT_LEDGER' 
					        AND DA.UPDATE_DATE = DD.UPDATE_DATE
					        AND DA.UPDATE_SEQ = DD.UPDATE_SEQ
					        AND DA.FIELD_NAME = 'CRE_DT'
					        AND DA.RECORD_SEQ = DD.RECORD_SEQ) CRE_DT,      
                 '' APPROVED_STATUS, ' ' APPROVED_BY,     
					(SELECT FIELD_VALUE FROM T_MANY_DETAIL DA 
					        WHERE DA.TABLE_NAME = 'T_ACCOUNT_LEDGER' 
					        AND DA.UPDATE_DATE = DD.UPDATE_DATE
					        AND DA.UPDATE_SEQ = DD.UPDATE_SEQ
					        AND DA.FIELD_NAME = 'FOLDER_CD'
					        AND DA.RECORD_SEQ = DD.RECORD_SEQ) FOLDER_CD,
				 '3' NORUT
					FROM T_MANY_DETAIL DD, T_MANY_HEADER HH 
          WHERE DD.TABLE_NAME = 'T_ACCOUNT_LEDGER' 
		AND HH.MENU_NAME='GL JOURNAL ENTRY'
          AND DD.UPDATE_DATE = HH.UPDATE_DATE
          AND DD.UPDATE_SEQ = HH.UPDATE_SEQ 
         AND DD.FIELD_NAME = 'DOC_DATE' AND HH.APPROVED_STATUS = 'E' 
         ORDER BY HH.UPDATE_SEQ ) A, ipnextg.mst_gl_account m
		 where trim(a.sl_acct_cd) = trim(m.sl_a) and trim(a.gl_acct_cd) = trim(m.gl_a)
     order by xn_doc_num
     
     