SELECT  CA_TYPE, STK_CD, CUM_DT,X_DT,RECORDING_DT,
			DISTRIB_DT ,CLIENT_CD, CLIENT_NAME, BRANCH_CODE,CLIENT_TYPE,											
     FROM_QTY, TO_QTY,BEGIN_QTY, RECV_QTY,	 END_QTY,												
	 CUM_BEGIN_QTY,	CUM_RECV_QTY, CUM_END_QTY,	RECV_QTY - CUM_RECV_QTY SEL_RECV,END_QTY - CUM_END_QTY AS SEL_END_QTY										
	--P_USER_ID, P_GENERATE_DATE, V_RANDOM_VALUE												
FROM(													
	SELECT  A.CLIENT_CD, A.STK_CD, CA_TYPE, FROM_QTY, TO_QTY,  CLIENT_TYPE, 												
	    BEGIN_QTY,												
		ROUND(A.BEGIN_QTY * TO_QTY/FROM_QTY,0) RECV_QTY,											
		DECODE(C.CA_TYPE,'SPLIT',0,'REVERSE',0,A.BEGIN_QTY) +ROUND(A.BEGIN_QTY * TO_QTY/FROM_QTY,0) END_QTY,											
		CUM_BEGIN_QTY, 											
		ROUND(CUM_BEGIN_QTY * TO_QTY/FROM_QTY,0) CUM_RECV_QTY,											
		DECODE(C.CA_TYPE,'SPLIT',0,'REVERSE',0,CUM_BEGIN_QTY) +ROUND(CUM_BEGIN_QTY * TO_QTY/FROM_QTY,0) CUM_END_QTY,
		M.CLIENT_NAME, M.BRANCH_CODE	,C.DISTRIB_DT, C.X_DT, C.RECORDING_DT, C.CUM_DT	
	FROM( 												
	SELECT CLIENT_CD, STK_CD,												
		   SUM( NVL(MVMT_QTY,0)) BEGIN_QTY,											
		   SUM(NVL(CUM_QTY,0))  CUM_BEGIN_QTY											
	FROM(	   											
		SELECT CLIENT_CD, STK_CD,  MVMT_QTY,											
		   	DECODE(SIGN(DOC_DT - TO_DATE(:P_CUM_DT,'YYYY-MM-DD')), 1, 0, MVMT_QTY) CUM_QTY										
		FROM(											
			   SELECT DOC_DT,  CLIENT_CD, STK_CD, 										
				  DECODE(SUBSTR(DOC_NUM,5,2),'BR',1,'JR',1,'BI',1,'JI',1,'BO',1,'JO',1,'RS',1,'WS',1,0) *									
				  DECODE(DB_CR_FLG,'D',1,-1) *  (TOTAL_SHARE_QTY + WITHDRAWN_SHARE_QTY) MVMT_QTY									
			      FROM IPNEXTG.T_STK_MOVEMENT 										
				  WHERE DOC_DT BETWEEN TO_DATE(:P_BGN_DT,'YYYY-MM-DD') AND TO_DATE(:P_RECORDING_DT,'YYYY-MM-DD')									
				  AND DOC_DT <= TO_DATE(:V_TODAY,'YYYY-MM-DD')									
				AND STK_CD = :P_STK_CD									
				AND TRIM(GL_ACCT_CD) IN ('10','12','13','14','51')									
				AND DOC_STAT    = '2' 									
				AND DUE_DT_FOR_CERT <= TO_DATE(:P_RECORDING_DT,'YYYY-MM-DD'))									
		 UNION ALL											
		SELECT  CLIENT_CD, STK_CD, BEG_BAL_QTY, BEG_BAL_QTY											
			FROM IPNEXTG.T_STKBAL										
			WHERE BAL_DT = TO_DATE(:P_BGN_DT,'YYYY-MM-DD')										
			AND STK_CD = :P_STK_CD) 										
	GROUP BY  CLIENT_CD, STK_CD												
	HAVING  SUM(MVMT_QTY) > 0												
	) A,												
	( SELECT CLIENT_CD,  DECODE(CLIENT_CD, C.COY_CLIENT_CD,'H', DECODE(CLIENT_TYPE_1,'H','H','%')) AS CLIENT_TYPE,CLIENT_NAME,BRANCH_CODE												
	  FROM IPNEXTG.MST_CLIENT, 												
		  ( SELECT TRIM(OTHER_1) COY_CLIENT_CD FROM IPNEXTG.MST_COMPANY) C											
	  WHERE CLIENT_TYPE_1 <> 'B'												
	 ) M,												
	  ( SELECT STK_CD, CA_TYPE, FROM_QTY, TO_QTY, DISTRIB_DT,X_DT, RECORDING_DT, CUM_DT												
	     FROM IPNEXTG.T_CORP_ACT												
	 WHERE STK_CD= :P_STK_CD												
	 AND CUM_DT = TO_DATE(:P_CUM_DT,'YYYY-MM-DD')												
	 AND CA_TYPE = :P_CA_TYPE												
	AND APPROVED_STAT = 'A') C												
WHERE A.CLIENT_CD = M.CLIENT_CD													
AND A.STK_CD = C.STK_CD );						