SELECT  A.UPDATE_DATE,A.UPDATE_SEQ INTO V_UPDATE_DATE,V_UPDATE_SEQ 
FROM
(SELECT  UPDATE_DATE,UPDATE_SEQ 
INTO V_UPDATE_DATE,V_UPDATE_SEQ 
FROM  T_TEMP_DETAIL  
WHERE  FIELD_NAME='BANK_ACCT_NUM'  
AND  FIELD_VALUE=  rec.rek_dana)  a,
(SELECT  UPDATE_DATE,UPDATE_SEQ 

FROM  T_TEMP_DETAIL  
WHERE  table_name 
AND  FIELD_NAME='CLIENT_CD'  
AND  FIELD_VALUE=rec.client_cd
)  b
WHERE  a.update_date =  b.update_date
	and a.update_seq=b.update_seq;