
  CREATE OR REPLACE FORCE VIEW "IPNEXTG"."V_GL_JOURNAL_INBOX" ("USER_ID", "UPDATE_DATE", "STATUS", "IP_ADDRESS", "JVCH_DATE", "FOLDER_CD", "JVCH_NUM", "CURR_AMT", "UPDATE_SEQ", "APPROVED_STATUS", "MENU_NAME", "APPROVED_DATE","REMARKS") AS 
  SELECT HH.USER_ID, HH.UPDATE_DATE, HH.STATUS, HH.IP_ADDRESS,
(SELECT FIELD_VALUE FROM T_MANY_DETAIL DA 
        WHERE DA.TABLE_NAME = 'T_JVCHH' 
        AND DA.UPDATE_DATE = DD.UPDATE_DATE
        AND DA.UPDATE_SEQ = DD.UPDATE_SEQ
        AND DA.FIELD_NAME = 'JVCH_DATE'
        AND DA.RECORD_SEQ = DD.RECORD_SEQ) JVCH_DATE, 
(SELECT FIELD_VALUE FROM T_MANY_DETAIL DA 
        WHERE DA.TABLE_NAME = 'T_JVCHH' 
        AND DA.UPDATE_DATE = DD.UPDATE_DATE
        AND DA.UPDATE_SEQ = DD.UPDATE_SEQ
        AND DA.FIELD_NAME = 'FOLDER_CD'
        AND DA.RECORD_SEQ = DD.RECORD_SEQ) FOLDER_CD,
(SELECT FIELD_VALUE FROM T_MANY_DETAIL DA 
        WHERE DA.TABLE_NAME = 'T_JVCHH' 
        AND DA.UPDATE_DATE = DD.UPDATE_DATE
        AND DA.UPDATE_SEQ = DD.UPDATE_SEQ
        AND DA.FIELD_NAME = 'JVCH_NUM'
        AND DA.RECORD_SEQ = DD.RECORD_SEQ) JVCH_NUM,
(SELECT FIELD_VALUE FROM T_MANY_DETAIL DA 
        WHERE DA.TABLE_NAME = 'T_JVCHH' 
        AND DA.UPDATE_DATE = DD.UPDATE_DATE
        AND DA.UPDATE_SEQ = DD.UPDATE_SEQ
        AND DA.FIELD_NAME = 'CURR_AMT'
        AND DA.RECORD_SEQ = DD.RECORD_SEQ) CURR_AMT,HH.UPDATE_SEQ,HH.APPROVED_STATUS,HH.MENU_NAME,HH.APPROVED_DATE,
(SELECT FIELD_VALUE FROM T_MANY_DETAIL DA 
        WHERE DA.TABLE_NAME = 'T_JVCHH' 
        AND DA.UPDATE_DATE = DD.UPDATE_DATE
        AND DA.UPDATE_SEQ = DD.UPDATE_SEQ
        AND DA.FIELD_NAME = 'REMARKS'
        AND DA.RECORD_SEQ = DD.RECORD_SEQ) REMARKS

FROM T_MANY_DETAIL DD, T_MANY_HEADER HH WHERE DD.TABLE_NAME = 'T_JVCHH' AND DD.UPDATE_DATE = HH.UPDATE_DATE
                      AND DD.UPDATE_SEQ = HH.UPDATE_SEQ AND DD.RECORD_SEQ = 1 AND DD.FIELD_NAME = 'JVCH_DATE' AND HH.APPROVED_STATUS = 'E' ORDER BY HH.UPDATE_SEQ;
 
